run_name: focal_a0_g5
run_tag: focal_a0_g5
timestamp: '2026-09-25T09:04:33'
repo_commit: c2b355ef8cf42a9914c64b5bb28a5584644ee260
data:
  input_dir: /content/drive/MyDrive/overlap_resolver/datas/np_arrays/HH_bbtt
  trainset_x_name: X_train_normalized.npy
  trainset_y_name: y_train_normalized.npy
  valset_x_name: X_val_normalized.npy
  valset_y_name: y_val_normalized.npy
  testset_x_name: X_test_normalized.npy
  testset_y_name: y_test_normalized.npy
  output_dir: null
  n_train: null
  n_val: null
  n_test: null
  sub_trainset_name: null
  sub_valset_name: null
  sub_testset_name: null
  n_overlap_couples: 377567
  n_features: 21
  class_names:
  - FF
  - FT
  - TF
  - TT
model:
  name: MLPMultiTagger
  hidden_dims:
  - 32
  - 16
  num_classes: 4
  norm_layer: LayerNorm
  dropout: 0.1
  activ_func: ReLU
training:
  criterion: CategoricalFocalLoss
  alpha_power: 0.0
  gamma: 5.0
  class_weights_p1: Tensor
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.7
    patience: 5
    mode: max
  max_epochs: 50
  early_stop_patience: 10
  min_delta_val_loss: 0.0001
  model_selection_metric: ap_macro
  seed: 42
  best_val_ap_macro: 0.7111012769741486
  best_val_ap_per_class:
  - 0.8608177456389121
  - 0.9965550979061287
  - 0.9524989982028712
  - 0.034533266148682185
  best_val_f1_macro: 0.6760836520238832
